#firehose-endpoint: localhost:9000
firehose-endpoint: fh.tekit.io:443
eos-endpoint: https://testnet.telos.caleos.io
elastic-endpoint: https://traceability.es.us-east4.gcp.elastic-cloud.com:9243 #username and password should be set using env vars ES_USER, ES_PASSWORD
elastic-ca: 
prometheus-port: 2114
start-block: 151824876
heart-beat-frequency: 100
#dfuse-api-key: server_eeb2882943ae420bfb3eb9bf3d78ed9d
cursor-index-prefix: testnet1

contracts:
- name: tlaclocmant2
  doc-table-name: documents
  index-prefix: traceability