#firehose-endpoint: localhost:9000
firehose-endpoint: telostest.firehose.eosnation.io:9000
eos-endpoint: https://testnet.telos.caleos.io
elastic-endpoint: https://localhost:9200 #username and password should be set using env vars ES_USER, ES_PASSWORD
elastic-ca: /home/sebastian/vsc-workspace/elastic-helm-charts/elasticsearch/examples/security/elastic-certificate.pem
prometheus-port: 2114
start-block: 147046658
heart-beat-frequency: 100
dfuse-api-key: dc6087c88050f3caeed46f22767c357c
dfuse-auth-url: https://auth.eosnation.io
cursor-index-prefix: dho-test
add-ints-as-strings: false

contracts:
- name: mtdhoxhyphaa
  doc-table-name: documents
  edge-table-name: edges
  index-prefix: dho-test
  edge-black-list:
  - from: "*"
    to: "Vote"
    name: "*"
    
single-text-search-field:
  asset: none
  checksum256: none
  int64: none
  name: none
  time_point: none
  string: none


  