#firehose-endpoint: localhost:9000
firehose-endpoint: fh.tekit.io:443
eos-endpoint: https://testnet.telos.caleos.io
elastic-endpoint: https://localhost:9200 #username and password should be set using env vars ES_USER, ES_PASSWORD
elastic-ca: certificates/ca/ca.crt
prometheus-port: 2114
start-block: 149760151
heart-beat-frequency: 100
#dfuse-api-key: server_eeb2882943ae420bfb3eb9bf3d78ed9d
cursor-index-prefix: testnet1

contracts:
- name: contract1
  doc-table-name: documents
  index-prefix: index1
- name: contract2
  doc-table-name: docs
  index-prefix: index2